Update onboarding doc
kubeflow/testing pull request #849
Opened 2021-01-18 17:10 UTC by PatrickXYS

**Which issue is resolved by this Pull Request:**
Resolves #

**Description of your changes:**
Update onboarding doc to not configure webhook anymore, since we have configured organization-level webhook.

**Checklist:**
If PR related to **Optional-Test-Infra**,

- [ ] Changes have been generated to `aws/GitOps` folder: 
    1. `cd aws`
    2. `make optional-generate`

2021-01-18 17:13 UTC, PatrickXYS commented
@theofpa Can you help approve?

2021-01-18 20:55 UTC, theofpa requested changes
thanks @PatrickXYS

2021-01-18 20:55 UTC, theofpa commented on aws/Doc/onboarding.md
> +Below is the steps for WG who want to write a generic E2E test cases
```suggestion
Below are the steps for WG who want to write a generic E2E test cases
```

2021-01-18 20:57 UTC, PatrickXYS commented on aws/Doc/onboarding.md
> +Below is the steps for WG who want to write a generic E2E test cases
Thanks, addressed in the new commit

2021-01-19 20:05 UTC, theofpa commented
/lgtm

2021-01-19 20:08 UTC, merged